name: Scrape InfoSec News

on:
  schedule:
    # Schedule to run every day at midnight (UTC)
    - cron: '0 0 * * *'

  workflow_dispatch: # Allow manual triggering of the action

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraping script
        run: |
          python scrape_news.py

      - name: Commit and push news data
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "GitHub Actions"
          git add news_data.json
          git commit -m "Update news data"
          git push